name: sss256
description: 'sss256 is a library with utilities for encode\decode secret with Shamir`s Secret Sharing algo'
version: 1.0.0
homepage: https://github.com/alexandrim0/sss256

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
